# Generated by Django 4.2.4 on 2023-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'Published')], default=0),
        ),
    ]
