# Generated by Django 4.2.4 on 2023-09-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
